apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: healthcheck
  name: healthcheck
spec:
  containers:
  - image: nginx
    name: healthcheck
    command:
      - /bin/bash
      - -c
      - |
        while true; do
            http_response=$(curl -s -o /dev/null -w "%{http_code}" "http://${BACKEND_API_SERVICE_HOST}/health_check")
            if [ "$http_response" == "200" ]; then
                echo "$(date): API at ${BACKEND_API_SERVICE_HOST} is reachable - Health check passed"
            else
                echo "$(date): API at ${BACKEND_API_SERVICE_HOST} is unreachable - Health check failed (HTTP $http_response)"
            fi
            sleep 30
        done
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
