apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.externalApiKey.name }}
  labels:
    {{- include "backend-api.labels" . | nindent 4 }}
type: Opaque
data:
  api_key: {{ .Values.secrets.externalApiKey.data.api_key | b64enc | quote }}
